# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "https://books.toscrape.com/"
response = requests.get(url)
response.status_code

200

In [3]:
soup = BeautifulSoup(response.text, "html.parser")
soup.title

<title>
    All products | Books to Scrape - Sandbox
</title>

In [4]:
soup.find_all("article", class_="product_pod")

[<article class="product_pod">
 <div class="image_container">
 <a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.77</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/tipping-the-velvet_999/index.html"><img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">Tipping the Velvet</a></h3>
 <div class="product_price">
 <p class="price_color">Â£53.74</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/soumission_998/index.html"><img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/soumission_998/index.html" title="Soumission">Soumission</a></h3>
 <div class="product_price">
 <p class="price_color">Â£50.10</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sharp-objects_997/index.html"><img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">Sharp Objects</a></h3>
 <div class="product_price">
 <p class="price_color">Â£47.82</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html"><img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">Sapiens: A Brief History ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£54.23</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-requiem-red_995/index.html"><img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">The Requiem Red</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.65</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html"><img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">The Dirty Little Secrets ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£33.34</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html"><img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html" title="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull">The Coming Woman: A ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.93</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html"><img alt="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics" class="thumbnail" src="media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html" title="The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics">The Boys in the ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£22.60</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/the-black-maria_991/index.html"><img alt="The Black Maria" class="thumbnail" src="media/cache/58/46/5846057e28022268153beff6d352b06c.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/the-black-maria_991/index.html" title="The Black Maria">The Black Maria</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.15</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html"><img alt="Starving Hearts (Triangular Trade Trilogy, #1)" class="thumbnail" src="media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html" title="Starving Hearts (Triangular Trade Trilogy, #1)">Starving Hearts (Triangular Trade ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£13.99</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/shakespeares-sonnets_989/index.html"><img alt="Shakespeare's Sonnets" class="thumbnail" src="media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg"/></a>
 </div>
 <p class="star-rating Four">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/shakespeares-sonnets_989/index.html" title="Shakespeare's Sonnets">Shakespeare's Sonnets</a></h3>
 <div class="product_price">
 <p class="price_color">Â£20.66</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/set-me-free_988/index.html"><img alt="Set Me Free" class="thumbnail" src="media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/set-me-free_988/index.html" title="Set Me Free">Set Me Free</a></h3>
 <div class="product_price">
 <p class="price_color">Â£17.46</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html"><img alt="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)" class="thumbnail" src="media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html" title="Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)">Scott Pilgrim's Precious Little ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£52.29</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/rip-it-up-and-start-again_986/index.html"><img alt="Rip it Up and Start Again" class="thumbnail" src="media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg"/></a>
 </div>
 <p class="star-rating Five">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/rip-it-up-and-start-again_986/index.html" title="Rip it Up and Start Again">Rip it Up and ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£35.02</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html"><img alt="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991" class="thumbnail" src="media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg"/></a>
 </div>
 <p class="star-rating Three">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html" title="Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991">Our Band Could Be ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£57.25</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/olio_984/index.html"><img alt="Olio" class="thumbnail" src="media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/olio_984/index.html" title="Olio">Olio</a></h3>
 <div class="product_price">
 <p class="price_color">Â£23.88</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html"><img alt="Mesaerion: The Best Science Fiction Stories 1800-1849" class="thumbnail" src="media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg"/></a>
 </div>
 <p class="star-rating One">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html" title="Mesaerion: The Best Science Fiction Stories 1800-1849">Mesaerion: The Best Science ...</a></h3>
 <div class="product_price">
 <p class="price_color">Â£37.59</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/libertarianism-for-beginners_982/index.html"><img alt="Libertarianism for Beginners" class="thumbnail" src="media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/libertarianism-for-beginners_982/index.html" title="Libertarianism for Beginners">Libertarianism for Beginners</a></h3>
 <div class="product_price">
 <p class="price_color">Â£51.33</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>,
 <article class="product_pod">
 <div class="image_container">
 <a href="catalogue/its-only-the-himalayas_981/index.html"><img alt="It's Only the Himalayas" class="thumbnail" src="media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg"/></a>
 </div>
 <p class="star-rating Two">
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 <i class="icon-star"></i>
 </p>
 <h3><a href="catalogue/its-only-the-himalayas_981/index.html" title="It's Only the Himalayas">It's Only the Himalayas</a></h3>
 <div class="product_price">
 <p class="price_color">Â£45.17</p>
 <p class="instock availability">
 <i class="icon-ok"></i>

         In stock

 </p>
 <form>
 <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
 </form>
 </div>
 </article>]

In [5]:
libros = soup.find_all("article", class_="product_pod")
len(libros)

20

In [6]:
libros[0].h3.a["title"]

'A Light in the Attic'

In [7]:
libros[0].find("p", class_="price_color").text

'Â£51.77'

In [8]:
libros[0].find("p", class_="star-rating")

<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>

In [9]:
libros[0].find("p", class_="star-rating")["class"]

['star-rating', 'Three']

In [10]:
libros[0].find("p", class_="star-rating")["class"][1]

'Three'

estrellas en numero

In [11]:
mapa_estrellas = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

In [12]:
palabra = libros[0].find("p", class_="star-rating")["class"][1]
mapa_estrellas[palabra]

3

juntar

In [13]:
libro = libros[0]

{
    "Title": libro.h3.a["title"],
    "Price": libro.find("p", class_="price_color").text,
    "Rating": mapa_estrellas[libro.find("p", class_="star-rating")["class"][1]]
}

{'Title': 'A Light in the Attic', 'Price': 'Â£51.77', 'Rating': 3}

In [14]:
datos = []

for libro in libros:
    diccionario = {
        "Title": libro.h3.a["title"],
        "Price": libro.find("p", class_="price_color").text,
        "Rating": mapa_estrellas[libro.find("p", class_="star-rating")["class"][1]]
    }
    datos.append(diccionario)

len(datos)

20

In [15]:
df = pd.DataFrame(datos)
df

                                                Title    Price  Rating
0                                A Light in the Attic  Â£51.77       3
1                                  Tipping the Velvet  Â£53.74       1
2                                          Soumission  Â£50.10       1
3                                       Sharp Objects  Â£47.82       4
4               Sapiens: A Brief History of Humankind  Â£54.23       5
5                                     The Requiem Red  Â£22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34       4
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93       3
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60       4
9                                     The Black Maria  Â£52.15       1
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99       2
11                              Shakespeare's Sonnets  Â£20.66       4
12                                        Set Me Free  Â£17.46       5
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29       5
14                          Rip it Up and Start Again  Â£35.02       5
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25       3
16                                               Olio  Â£23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59       1
18                       Libertarianism for Beginners  Â£51.33       2
19                            It's Only the Himalayas  Â£45.17       2

In [16]:
url = "https://books.toscrape.com/"
response = requests.get(url)
response.encoding = "utf-8"
response.status_code

200

In [17]:
soup = BeautifulSoup(response.text, "html.parser")
libros = soup.find_all("article", class_="product_pod")
len(libros)

20

In [18]:
mapa_estrellas = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

In [19]:
datos = []

for libro in libros:
    diccionario = {
        "Title": libro.h3.a["title"],
        "Price": float(libro.find("p", class_="price_color").text.replace("£", "")),
        "Rating": mapa_estrellas[libro.find("p", class_="star-rating")["class"][1]]
    }
    datos.append(diccionario)

df = pd.DataFrame(datos)
df

                                                Title  Price  Rating
0                                A Light in the Attic  51.77       3
1                                  Tipping the Velvet  53.74       1
2                                          Soumission  50.10       1
3                                       Sharp Objects  47.82       4
4               Sapiens: A Brief History of Humankind  54.23       5
5                                     The Requiem Red  22.65       1
6   The Dirty Little Secrets of Getting Your Dream...  33.34       4
7   The Coming Woman: A Novel Based on the Life of...  17.93       3
8   The Boys in the Boat: Nine Americans and Their...  22.60       4
9                                     The Black Maria  52.15       1
10     Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2
11                              Shakespeare's Sonnets  20.66       4
12                                        Set Me Free  17.46       5
13  Scott Pilgrim's Precious Little Life (Scott Pi...  52.29       5
14                          Rip it Up and Start Again  35.02       5
15  Our Band Could Be Your Life: Scenes from the A...  57.25       3
16                                               Olio  23.88       1
17  Mesaerion: The Best Science Fiction Stories 18...  37.59       1
18                       Libertarianism for Beginners  51.33       2
19                            It's Only the Himalayas  45.17       2

In [20]:
df.dtypes

Title         str
Price     float64
Rating      int64
dtype: object

In [21]:
df[(df["Rating"] >= 4) & (df["Price"] <= 20)]

          Title  Price  Rating
12  Set Me Free  17.46       5

In [22]:
enlace = libros[0].h3.a["href"]
url_libro = "https://books.toscrape.com/" + enlace
url_libro

'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

In [23]:
resp_libro = requests.get(url_libro)
resp_libro.encoding = "utf-8"
soup_libro = BeautifulSoup(resp_libro.text, "html.parser")
soup_libro.title

<title>
    A Light in the Attic | Books to Scrape - Sandbox
</title>

In [24]:
filas = soup_libro.find_all("td")
upc = filas[0].text

genero = soup_libro.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()

disponibilidad = soup_libro.find("p", class_="availability").text.strip()

descripcion = soup_libro.find("div", id="product_description").find_next_sibling("p").text

upc, genero, disponibilidad, descripcion

('a897fe39b1053632',
 'Poetry',
 'In stock (22 available)',
 "It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more")

In [25]:
def datos_detalle(url_libro):
    resp = requests.get(url_libro)
    resp.encoding = "utf-8"
    s = BeautifulSoup(resp.text, "html.parser")

    upc = s.find_all("td")[0].text
    genero = s.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()
    disponibilidad = s.find("p", class_="availability").text.strip()
    bloque = s.find("div", id="product_description")
    descripcion = bloque.find_next_sibling("p").text if bloque else ""

    return {"UPC": upc, "Genre": genero, "Availability": disponibilidad, "Description": descripcion}

In [26]:
datos = []

for libro in libros:
    diccionario = {
        "Title": libro.h3.a["title"],
        "Price": float(libro.find("p", class_="price_color").text.replace("£", "")),
        "Rating": mapa_estrellas[libro.find("p", class_="star-rating")["class"][1]]
    }
    url_libro = "https://books.toscrape.com/" + libro.h3.a["href"]
    diccionario.update(datos_detalle(url_libro))
    datos.append(diccionario)

df = pd.DataFrame(datos)
df

,Title,Price,Rating,UPC,Genre,Availability,Description
0,A Light in the Attic,51.77,3,a897fe39b1053632,Poetry,In stock (22 available),It's hard to imagine a world without A Light i...
1,Tipping the Velvet,53.74,1,90fa61229261140a,Historical Fiction,In stock (20 available),"""Erotic and absorbing...Written with starling ..."
2,Soumission,50.10,1,6957f44c3847a760,Fiction,In stock (20 available),"Dans une France assez proche de la nôtre, un h..."
3,Sharp Objects,47.82,4,e00eb4fd7b871a48,Mystery,In stock (20 available),"WICKED above her hipbone, GIRL across her hear..."
4,Sapiens: A Brief History of Humankind,54.23,5,4165285e1663650f,History,In stock (20 available),From a renowned historian comes a groundbreaki...
5,The Requiem Red,22.65,1,f77dbf2323deb740,Young Adult,In stock (19 available),Patient Twenty-nine.A monster roams the halls ...
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,2597b5a345f45e1b,Business,In stock (19 available),Drawing on his extensive experience evaluating...
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,e72a5dfc7e9267b2,Default,In stock (19 available),"""If you have a heart, if you have a soul, Kare..."
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,e10e1e165dc8be4a,Default,In stock (19 available),For readers of Laura Hillenbrand's Seabiscuit ...
9,The Black Maria,52.15,1,1dfe412b8ac00530,Poetry,In stock (19 available),"Praise for Aracelis Girmay:""[Girmay's] every l..."
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,2,0312262ecafa5a40,Default,In stock (19 available),"Since her assault, Miss Annette Chetwynd has b..."
11,Shakespeare's Sonnets,20.66,4,30a7f60cd76ca58c,Poetry,In stock (19 available),This book is an important and complete collect...
12,Set Me Free,17.46,5,ce6396b0f23f6ecc,Young Adult,In stock (19 available),Aaron Ledbetter’s future had been planned out ...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,3b1c02bac2a429e6,Sequential Art,In stock (19 available),Scott Pilgrim's life is totally sweet. He's 23...
14,Rip it Up and Start Again,35.02,5,a34ba96d4081e6a4,Music,In stock (19 available),"Punk's raw power rejuvenated rock, but by the ..."
15,Our Band Could Be Your Life: Scenes from the A...,57.25,3,deda3e61b9514b83,Music,In stock (19 available),This is the never-before-told story of the mus...
16,Olio,23.88,1,feb7cc7701ecf901,Poetry,In stock (19 available),"Part fact, part fiction, Tyehimba Jess's much ..."
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,1,e30f54cea9b38190,Science Fiction,In stock (19 available),"Andrew Barger, award-winning author and engine..."
18,Libertarianism for Beginners,51.33,2,a18a4f574854aced,Politics,In stock (19 available),Libertarianism isn't about winning elections; ...
19,It's Only the Himalayas,45.17,2,a22124811bfa8350,Travel,In stock (19 available),"“Wherever you go, whatever you do, just . . . ..."

In [27]:
from urllib.parse import urljoin

def scrape_books(min_rating, max_price):
    datos = []

    for pagina in range(1, 51):
        url_pagina = f"https://books.toscrape.com/catalogue/page-{pagina}.html"
        resp = requests.get(url_pagina)
        resp.encoding = "utf-8"
        s = BeautifulSoup(resp.text, "html.parser")

        for libro in s.find_all("article", class_="product_pod"):
            rating = mapa_estrellas[libro.find("p", class_="star-rating")["class"][1]]
            precio = float(libro.find("p", class_="price_color").text.replace("£", ""))

            if rating >= min_rating and precio <= max_price:
                diccionario = {
                    "Title": libro.h3.a["title"],
                    "Price": precio,
                    "Rating": rating
                }
                url_libro = urljoin(url_pagina, libro.h3.a["href"])
                diccionario.update(datos_detalle(url_libro))
                datos.append(diccionario)

    return pd.DataFrame(datos)

In [28]:
resultado = scrape_books(4, 20)
resultado

,Title,Price,Rating,UPC,Genre,Availability,Description
0,Set Me Free,17.46,5,ce6396b0f23f6ecc,Young Adult,In stock (19 available),Aaron Ledbetter’s future had been planned out ...
1,The Four Agreements: A Practical Guide to Pers...,17.66,5,6258a1f6a6dcfe50,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,Sophie's World,15.94,5,6be3beb0793a53e7,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,Untitled Collection: Sabbath Poems 2014,14.27,4,657fe5ead67a7767,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,This One Summer,19.49,4,51653ef291ab7ddc,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."
...,...,...,...,...,...,...,...
70,The Zombie Room,19.69,5,9c96cd1329fbd82d,Default,In stock (1 available),An unlikely bond is forged between three men f...
71,The Silent Wife,12.34,5,b78deb463531d078,Fiction,In stock (1 available),A chilling psychological thriller about a marr...
72,The Girl You Lost,12.29,5,4280ac3eab57aa5d,Mystery,In stock (1 available),Eighteen years ago your baby daughter was snat...
73,The Edge of Reason (Bridget Jones #2),19.18,4,29fc016c459aeb14,Womens Fiction,In stock (1 available),Monday 27 January“7:15 a.m. Hurrah! The wilder...
74,A Spy's Devotion (The Regency Spies of London #1),16.97,5,19fec36a1dfb4c16,Historical Fiction,In stock (1 available),"In England’s Regency era, manners and elegance..."

In [29]:
resultado2 = scrape_books(5, 10)
resultado2

,Title,Price,Rating,UPC,Genre,Availability,Description
0,An Abundance of Katherines,10.0,5,f36d24c309e87e5b,Young Adult,In stock (5 available),Katherine V thought boys were gross Katherine ...